### ISSUE TITLE
Bug: restarting the server loses all active sessions

### ISSUE THREAD

**Issue by googol** [partio-scout/reki#231]

**Comment by googol** [comment]
Fixed by adding redis for session data storage in production

**Comment by emilvirkki** [comment]
Should this be documented also in the setup instructions? :)

**Comment by googol** [comment]
No need to, if you follow the instructions and use the deploy button, the redis add on will be automatically created :)

**Comment by emilvirkki** [comment]
Ooh, nice 👌
